# Generated by Django 5.2.6 on 2025-10-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0006_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='user_name',
        ),
    ]
