# Generated by Django 5.2.6 on 2025-10-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0008_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
