# Generated by Django 5.2.6 on 2025-11-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0015_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reward_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reward_awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claim', to='foodsite.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsite.user')),
            ],
            options={
                'db_table': 'reward_claims',
            },
        ),
    ]
